version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/myapp
    steps:
      - checkout
      - run: java -version
      - run: mvn test
    branches:
      only:
        - master
