# config.yml

version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: target/site/apidocs/
          destination: javadoc
  generate-javadoc:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/site/apidocs/
          name: javadoc

workflows:
  verification:
    jobs:
      - build-and-test
      - generate-javadoc:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-gh-pages:
          requires:
            - generate-javadoc
          filters:
            branches:
              only: master

orbs:
  gh-pages: circleci/gh-pages@1.1.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Publish orb
          command: |
            mkdir -p $HOME/.circleci
            echo -n $CIRCLECI_ORB_REGISTRY_TOKEN > $HOME/.circleci/orb_token
            circleci orb publish orb.yml circleci/gh-pages@1.1.1

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          filters:
            branches:
              only: master
