version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - codecov/upload
      - attach_workspace:
          at: /tmp/workspace
      - store_artifacts:
          path: target/site/apidocs/
          destination: javadoc
  generate-javadoc:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Générer la documentation Java
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - target/site/apidocs/
          name: javadoc

workflows:
  verification:
    jobs:
      - build-and-test
      - generate-javadoc:
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - deploy-gh-pages:
          requires:
            - generate-javadoc
          filters:
            branches:
              only: master
